# Conexión a PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5433/motorhunt
spring.datasource.username=admin
spring.datasource.password=admin123

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=motorhunt-secret-key-super-secure-motorhunt-secret-key-super-secure
jwt.expiration=86400000