
services:
  postgres:
    image: postgres:15
    container_name: motorhunt_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: motorhunt
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d  # Scripts de inicialización
volumes:
  pgdata: